name: Repository Dispatch Listener

on:
  repository_dispatch:
    types: [custom-event, iniciar-evento]  # tipo de evento personalizado

jobs:
  run-on-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event data
        run: |
          echo "Disparado via repository_dispatch"
          echo "Evento: ${{ github.event.action }}"
          echo "Payload: ${{ toJson(github.event.client_payload) }}"
          echo "Custom Input: ${{ github.event.client_payload.a }}"
      - name: Roda
        if: ${{ github.event.action == 'custom-event' }}
        run: |
          echo "Roda o evento customizado"
          echo "tipo: ${{ github.event.client_payload.custom }}"
      - name: Iniciar
        if: ${{ github.event.action == 'iniciar-evento' }}
        run: |
          echo "Inicia o evento"
          echo "tipo: ${{ github.event.client_payload.iniciado }}"




#           curl --location 'https://api.github.com/repos/julianooen/teste-novo-git-actions/dispatches' \
# --header 'Accept: application/vnd.github+json' \
# --header 'Authorization: token meu_token' \
# --header 'Content-Type: application/json' \
# --data '{
#   "event_type": "iniciar-evento",
#   "event_type": "custom-event",
#   "client_payload": {
#     "mensagem": "Olá do Postman",
#     "a": "eu sou o a",
#     "iniciado": "vim do evento iniciado",
#     "custom": "vim do custom"
#   }
# }'