name: Repository Dispatch Listener

on:
  repository_dispatch:
    types: [custom-event, iniciar-evento]  # tipo de evento personalizado

jobs:
  run-on-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event data
        run: |
          echo "Disparado via repository_dispatch"
          echo "Evento: ${{ github.event.action }}"
          echo "Payload: ${{ toJson(github.event.corpo) }}"
          echo "Custom Input: ${{ github.event.corpo.a }}"
