name: Repository Dispatch
on:
  repository_dispatch:
    types: [run-workflow]
jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Print event type
        run: echo "Event type: ${{ github.event.action }}"