name: Testes de Variáveis e Outros
run-name: Testes variados de revisão
on:
  workflow_dispatch:
    inputs:
      var1:
        description: 'insira a variavel 1'
        required: true
        default: 'não teve entrada de valor'
jobs:
  teste:
    runs-on: ubuntu-latest
    outputs:
      local1: ${{ steps.exibir-variaveis.outputs.LOCAL1}}
    steps:
      - name: Exibir variáveis
        id: exibir-variaveis
        run: |
          echo " ${{ github.event.inputs.var1 }}"
          echo "LOCAL1=${{ github.event.inputs.var1 }}" >> $GITHUB_OUTPUT
          echo "$GITHUB_OUTPUT"
  fim:
    runs-on: ubuntu-latest
    needs: teste
    steps:
      - name: Exibir variáveis do job anterior
        run: |
          echo " ${{ needs.teste.outputs.local1}}"