name: 01 - Building Blocks
on: [push, workflow_dispatch]
jobs:

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Say goodbye
        run: echo "Goodbye!"
      - name: Failed step
        run: |
          echo "I will fail"
          exit 1




  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, World!"
  
        