name: 04 - Using Actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Printing Folders
        run: |
          echo "Current directory:"
          pwd
          echo "Files in current directory:"
          ls -la
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Move to folder
        run: |
          cd 04-using-actions/react-app
          pwd
