name: 05 - 2 - Event Filters and Activity Types
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Message when closing PR
        run: echo "Running whenever a PR is closed on main or master branch"