name: 16 - Working with Environments
on: 
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging
run-name: 16 - Working with Environments | env - ${{ github.event.inputs.target-env }}
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default-value' }}
    steps:
      - name: Echo vars
        run: echo "Deploying to staging"

  e2e-tests:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Echo vars
        run: echo "Running E2E tests"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: e2e-tests
    environment: prod
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default-value' }}
    steps:
      - name: Echo vars
        run: echo "Deploying to prod"